media_folder: "../../public/decap/"
# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: cfuenlabs/soft001
  branch: main
  identity_url: https://auth.decapbridge.com/sites/ef8d8d2c-4096-4db6-89d0-bb1f88dd3048
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

collections:
  - name: "categorias"
    label: "Categorías"
    folder: "_data/categorias"
    create: true
    slug: "{{slug}}"
    identifier_field: "nombre"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }

  - name: "productos"
    label: "Productos"
    folder: "_data/productos"
    create: true
    slug: "{{slug}}"
    identifier_field: "nombre"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - {
          label: "Tipo",
          name: "tipo",
          widget: "select",
          options: ["simple", "con colores"],
          default: "simple"
        }
      - {
          label: "Categoría",
          name: "categoria",
          widget: "relation",
          collection: "categorias",
          search_fields: ["nombre"],
          value_field: "nombre",
          display_fields: ["nombre"],
          required: true
        }
      - { label: "Precio", name: "precio", widget: "number" }
      - {
          label: "Almacenamiento",
          name: "almacenamiento",
          widget: "list",
          allow_add: true,
          collapsed: false,
          label_singular: "Almacenamiento",
          fields: [
            { label: "Almacenamiento", name: "almacenamiento", widget: "string" }
          ]
        }

      # Image for simple products (always shown)
      - {
          label: "Imagen principal",
          name: "imagen_principal",
          widget: "image",
          required: false
        }

      # Colorful product fields (always shown but can be empty)
      - {
          label: "Imágenes por color",
          name: "imagenes_colores",
          widget: "list",
          allow_add: true,
          collapsed: false,
          label_singular: "imagen con color",
          fields: [
            { label: "Imagen", name: "imagen", widget: "image" },
            { label: "Nombre del color", name: "nombre_color", widget: "string" }
          ]
        }
      - {
          label: "Colores disponibles",
          name: "colores_disponibles",
          widget: "list",
          allow_add: true,
          collapsed: true,
          summary: "{{fields.nombre}} ({{fields.valor}})",
          label_singular: "color",
          fields: [
            { label: "Color", name: "valor", widget: "color" },
            { label: "Nombre", name: "nombre", widget: "string" }
          ]
        }


# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://iphoneshop-co.netlify.app
